package ru.scuroneko.furniture.registry.items.cases

import net.minecraft.block.Blocks
import net.minecraft.item.Item
import ru.scuroneko.furniture.api.registry.autoregistry.IItemContainer
import ru.scuroneko.furniture.item.KitchenDrawerCaseItem
import ru.scuroneko.furniture.registry.RegistryHelper

object KitchenDrawersCases : IItemContainer {
    // Oak planks
    val WHITE_OAK_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_OAK_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_OAK_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_OAK_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.POLISHED_TUFF)

    // Oak log
    val WHITE_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_TUFF)

    // Stripped oak log
    val WHITE_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.POLISHED_TUFF)

    // Spruce planks
    val WHITE_SPRUCE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_SPRUCE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_SPRUCE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_SPRUCE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_SPRUCE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_SPRUCE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_SPRUCE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_SPRUCE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.POLISHED_TUFF)

    // Spruce log
    val WHITE_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_TUFF)

    // Stripped spruce log
    val WHITE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.POLISHED_TUFF)

    // Birch planks
    val WHITE_BIRCH_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_BIRCH_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_BIRCH_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_BIRCH_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_BIRCH_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_BIRCH_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_BIRCH_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_BIRCH_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.POLISHED_TUFF)

    // Birch log
    val WHITE_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_TUFF)

    // Stripped birch log
    val WHITE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.POLISHED_TUFF)

    // Jungle planks
    val WHITE_JUNGLE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_JUNGLE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_JUNGLE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_JUNGLE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_JUNGLE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_JUNGLE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_JUNGLE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_JUNGLE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.POLISHED_TUFF)

    // Jungle log
    val WHITE_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_TUFF)

    // Stripped jungle log
    val WHITE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.POLISHED_TUFF)

    // Acacia planks
    val WHITE_ACACIA_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_ACACIA_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_ACACIA_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_ACACIA_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_ACACIA_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_ACACIA_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_ACACIA_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_ACACIA_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.POLISHED_TUFF)

    // Acacia log
    val WHITE_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_TUFF)

    // Stripped acacia log
    val WHITE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.POLISHED_TUFF)

    // Dark oak planks
    val WHITE_DARK_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_DARK_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_DARK_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_DARK_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_DARK_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_DARK_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_DARK_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_DARK_OAK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_TUFF)

    // Dark oak log
    val WHITE_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_TUFF)

    // Stripped dark oak log
    val WHITE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.POLISHED_TUFF)

    // Mangrove planks
    val WHITE_MANGROVE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_MANGROVE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_MANGROVE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_MANGROVE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_MANGROVE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_MANGROVE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_MANGROVE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_MANGROVE_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.POLISHED_TUFF)

    // Mangrove log
    val WHITE_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_TUFF)

    // Stripped mangrove log
    val WHITE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.POLISHED_TUFF)

    // Cherry planks
    val WHITE_CHERRY_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_CHERRY_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_CHERRY_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_CHERRY_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_CHERRY_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_CHERRY_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_CHERRY_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_CHERRY_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.POLISHED_TUFF)

    // Cherry log
    val WHITE_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_TUFF)

    // Stripped cherry log
    val WHITE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.POLISHED_TUFF)

    // Bamboo planks
    val WHITE_BAMBOO_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_BAMBOO_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_BAMBOO_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_BAMBOO_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_BAMBOO_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_BAMBOO_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_BAMBOO_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_BAMBOO_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Blocks.POLISHED_TUFF)

    // Bamboo block
    val WHITE_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_TUFF)

    // Stripped bamboo block
    val WHITE_STRIPPED_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_BAMBOO_BLOCK_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_BAMBOO_BLOCK, Blocks.BAMBOO_SLAB, Blocks.POLISHED_TUFF)

    // Bamboo mosaic
    val WHITE_BAMBOO_MOSAIC_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_BAMBOO_MOSAIC_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_BAMBOO_MOSAIC_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_BAMBOO_MOSAIC_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_BAMBOO_MOSAIC_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_BAMBOO_MOSAIC_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_BAMBOO_MOSAIC_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_BAMBOO_MOSAIC_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_SLAB, Blocks.POLISHED_TUFF)

    // Crimson planks
    val WHITE_CRIMSON_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_CRIMSON_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_CRIMSON_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_CRIMSON_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_CRIMSON_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_CRIMSON_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_CRIMSON_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_CRIMSON_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Blocks.POLISHED_TUFF)

    // Crimson stem
    val WHITE_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_TUFF)

    // Stripped crimson
    val WHITE_STRIPPED_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_CRIMSON_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_CRIMSON_STEM, Blocks.CRIMSON_SLAB, Blocks.POLISHED_TUFF)

    // Warped planks
    val WHITE_WARPED_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_WARPED_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_WARPED_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_WARPED_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_WARPED_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_WARPED_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_WARPED_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_WARPED_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Blocks.POLISHED_TUFF)

    // Crimson stem
    val WHITE_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_STEM, Blocks.WARPED_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_STEM, Blocks.WARPED_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_STEM, Blocks.WARPED_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_TUFF)

    // Stripped crimson
    val WHITE_STRIPPED_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_WARPED_STEM, Blocks.WARPED_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_WARPED_STEM, Blocks.WARPED_SLAB, Blocks.BLACK_CONCRETE)
    val STONE_STRIPPED_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_WARPED_STEM, Blocks.WARPED_SLAB, Blocks.SMOOTH_STONE)
    val GRANITE_STRIPPED_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_GRANITE)
    val DIORITE_STRIPPED_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_DIORITE)
    val ANDESITE_STRIPPED_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_ANDESITE)
    val DEEPSLATE_STRIPPED_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_DEEPSLATE)
    val TUFF_STRIPPED_WARPED_STEM_KITCHEN_DRAWER_CASE =
        KitchenDrawerCaseItem(Blocks.STRIPPED_WARPED_STEM, Blocks.WARPED_SLAB, Blocks.POLISHED_TUFF)

    override fun afterEach(obj: Item) {
        RegistryHelper.Items.KITCHEN_DRAWERS_CASES.add(obj as KitchenDrawerCaseItem)
        RegistryHelper.Items.ITEMS.add(obj)
    }
}