package ru.scuroneko.furniture.registry.blocks

import net.minecraft.block.Block
import ru.scuroneko.furniture.ModItems
import ru.scuroneko.furniture.blocks.KitchenDrawerBlock
import ru.scuroneko.furniture.registry.RegistryHelper
import ru.scuroneko.asakusalib.api.registry.IBlocksContainer

object KitchenDrawers: IBlocksContainer {
    val BLACK_OAK_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_OAK_KITCHEN_DRAWER_CASE, ModItems.OAK_MEDIUM_DRAWER_BOX)
    val WHITE_OAK_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_OAK_KITCHEN_DRAWER_CASE, ModItems.OAK_MEDIUM_DRAWER_BOX)
    val BLACK_OAK_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_OAK_LOG_KITCHEN_DRAWER_CASE, ModItems.OAK_MEDIUM_DRAWER_BOX)
    val WHITE_OAK_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_OAK_LOG_KITCHEN_DRAWER_CASE, ModItems.OAK_MEDIUM_DRAWER_BOX)
    val BLACK_STRIPPED_OAK_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE, ModItems.OAK_MEDIUM_DRAWER_BOX)
    val WHITE_STRIPPED_OAK_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE, ModItems.OAK_MEDIUM_DRAWER_BOX)

    val BLACK_SPRUCE_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_SPRUCE_KITCHEN_DRAWER_CASE, ModItems.SPRUCE_MEDIUM_DRAWER_BOX)
    val WHITE_SPRUCE_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_SPRUCE_KITCHEN_DRAWER_CASE, ModItems.SPRUCE_MEDIUM_DRAWER_BOX)
    val BLACK_SPRUCE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_SPRUCE_LOG_KITCHEN_DRAWER_CASE, ModItems.SPRUCE_MEDIUM_DRAWER_BOX)
    val WHITE_SPRUCE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_SPRUCE_LOG_KITCHEN_DRAWER_CASE, ModItems.SPRUCE_MEDIUM_DRAWER_BOX)
    val BLACK_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE, ModItems.SPRUCE_MEDIUM_DRAWER_BOX)
    val WHITE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE, ModItems.SPRUCE_MEDIUM_DRAWER_BOX)

    val BLACK_BIRCH_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_BIRCH_KITCHEN_DRAWER_CASE, ModItems.BIRCH_MEDIUM_DRAWER_BOX)
    val WHITE_BIRCH_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_BIRCH_KITCHEN_DRAWER_CASE, ModItems.BIRCH_MEDIUM_DRAWER_BOX)
    val BLACK_BIRCH_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_BIRCH_LOG_KITCHEN_DRAWER_CASE, ModItems.BIRCH_MEDIUM_DRAWER_BOX)
    val WHITE_BIRCH_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_BIRCH_LOG_KITCHEN_DRAWER_CASE, ModItems.BIRCH_MEDIUM_DRAWER_BOX)
    val BLACK_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE, ModItems.BIRCH_MEDIUM_DRAWER_BOX)
    val WHITE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE, ModItems.BIRCH_MEDIUM_DRAWER_BOX)

    val BLACK_JUNGLE_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_JUNGLE_KITCHEN_DRAWER_CASE, ModItems.JUNGLE_MEDIUM_DRAWER_BOX)
    val WHITE_JUNGLE_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_JUNGLE_KITCHEN_DRAWER_CASE, ModItems.JUNGLE_MEDIUM_DRAWER_BOX)
    val BLACK_JUNGLE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_JUNGLE_LOG_KITCHEN_DRAWER_CASE, ModItems.JUNGLE_MEDIUM_DRAWER_BOX)
    val WHITE_JUNGLE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_JUNGLE_LOG_KITCHEN_DRAWER_CASE, ModItems.JUNGLE_MEDIUM_DRAWER_BOX)
    val BLACK_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE, ModItems.JUNGLE_MEDIUM_DRAWER_BOX)
    val WHITE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE, ModItems.JUNGLE_MEDIUM_DRAWER_BOX)

    val BLACK_ACACIA_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_ACACIA_KITCHEN_DRAWER_CASE, ModItems.ACACIA_MEDIUM_DRAWER_BOX)
    val WHITE_ACACIA_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_ACACIA_KITCHEN_DRAWER_CASE, ModItems.ACACIA_MEDIUM_DRAWER_BOX)
    val BLACK_ACACIA_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_ACACIA_LOG_KITCHEN_DRAWER_CASE, ModItems.ACACIA_MEDIUM_DRAWER_BOX)
    val WHITE_ACACIA_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_ACACIA_LOG_KITCHEN_DRAWER_CASE, ModItems.ACACIA_MEDIUM_DRAWER_BOX)
    val BLACK_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE, ModItems.ACACIA_MEDIUM_DRAWER_BOX)
    val WHITE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE, ModItems.ACACIA_MEDIUM_DRAWER_BOX)

    val BLACK_DARK_OAK_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_DARK_OAK_KITCHEN_DRAWER_CASE, ModItems.DARK_OAK_MEDIUM_DRAWER_BOX)
    val WHITE_DARK_OAK_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_DARK_OAK_KITCHEN_DRAWER_CASE, ModItems.DARK_OAK_MEDIUM_DRAWER_BOX)
    val BLACK_DARK_OAK_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_DARK_OAK_LOG_KITCHEN_DRAWER_CASE, ModItems.DARK_OAK_MEDIUM_DRAWER_BOX)
    val WHITE_DARK_OAK_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_DARK_OAK_LOG_KITCHEN_DRAWER_CASE, ModItems.DARK_OAK_MEDIUM_DRAWER_BOX)
    val BLACK_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE, ModItems.DARK_OAK_MEDIUM_DRAWER_BOX)
    val WHITE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE, ModItems.DARK_OAK_MEDIUM_DRAWER_BOX)

    val BLACK_MANGROVE_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_MANGROVE_KITCHEN_DRAWER_CASE, ModItems.MANGROVE_MEDIUM_DRAWER_BOX)
    val WHITE_MANGROVE_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_MANGROVE_KITCHEN_DRAWER_CASE, ModItems.MANGROVE_MEDIUM_DRAWER_BOX)
    val BLACK_MANGROVE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_MANGROVE_LOG_KITCHEN_DRAWER_CASE, ModItems.MANGROVE_MEDIUM_DRAWER_BOX)
    val WHITE_MANGROVE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_MANGROVE_LOG_KITCHEN_DRAWER_CASE, ModItems.MANGROVE_MEDIUM_DRAWER_BOX)
    val BLACK_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE, ModItems.MANGROVE_MEDIUM_DRAWER_BOX)
    val WHITE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE, ModItems.MANGROVE_MEDIUM_DRAWER_BOX)

    val BLACK_CHERRY_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_CHERRY_KITCHEN_DRAWER_CASE, ModItems.CHERRY_MEDIUM_DRAWER_BOX)
    val WHITE_CHERRY_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_CHERRY_KITCHEN_DRAWER_CASE, ModItems.CHERRY_MEDIUM_DRAWER_BOX)
    val BLACK_CHERRY_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_CHERRY_LOG_KITCHEN_DRAWER_CASE, ModItems.CHERRY_MEDIUM_DRAWER_BOX)
    val WHITE_CHERRY_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_CHERRY_LOG_KITCHEN_DRAWER_CASE, ModItems.CHERRY_MEDIUM_DRAWER_BOX)
    val BLACK_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.BLACK_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE, ModItems.CHERRY_MEDIUM_DRAWER_BOX)
    val WHITE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER = KitchenDrawerBlock(ModItems.WHITE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE, ModItems.CHERRY_MEDIUM_DRAWER_BOX)

    override fun onRegistry(block: Block) {
        RegistryHelper.Blocks.KITCHEN_DRAWERS.add(block as KitchenDrawerBlock)
    }
}