package ru.scuroneko.furniture

import net.minecraft.block.Blocks
import net.minecraft.item.Item
import net.minecraft.util.Identifier
import ru.scuroneko.furniture.item.BoxItem
import ru.scuroneko.furniture.item.KitchenDrawerCaseItem
import ru.scuroneko.furniture.item.MedicalDrawerCaseItem
import ru.scuroneko.furniture.registry.KitchenDrawersComponents.BOX_LIST
import ru.scuroneko.furniture.registry.KitchenDrawersComponents.CASE_LIST
import ru.scuroneko.furniture.registry.RegistryHelper
import ru.scuroneko.asakusalib.api.registry.IItemContainer

object ModItems: IItemContainer {
    val OAK_MEDIUM_DRAWER_BOX = BoxItem(Blocks.OAK_SLAB)
    val WHITE_OAK_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_OAK_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.OAK_LOG, Blocks.OAK_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_OAK_LOG, Blocks.OAK_SLAB, Blocks.BLACK_CONCRETE)

    val SPRUCE_MEDIUM_DRAWER_BOX = BoxItem(Blocks.SPRUCE_SLAB)
    val WHITE_SPRUCE_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_SPRUCE_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_SPRUCE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_SPRUCE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_SPRUCE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_SPRUCE_LOG, Blocks.SPRUCE_SLAB, Blocks.BLACK_CONCRETE)

    val BIRCH_MEDIUM_DRAWER_BOX = BoxItem(Blocks.BIRCH_SLAB)
    val WHITE_BIRCH_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_BIRCH_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_BIRCH_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_BIRCH_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_BIRCH_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_BIRCH_LOG, Blocks.BIRCH_SLAB, Blocks.BLACK_CONCRETE)

    val JUNGLE_MEDIUM_DRAWER_BOX = BoxItem(Blocks.JUNGLE_SLAB)
    val WHITE_JUNGLE_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_JUNGLE_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_JUNGLE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_JUNGLE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_JUNGLE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_JUNGLE_LOG, Blocks.JUNGLE_SLAB, Blocks.BLACK_CONCRETE)

    val ACACIA_MEDIUM_DRAWER_BOX = BoxItem(Blocks.ACACIA_SLAB)
    val WHITE_ACACIA_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_ACACIA_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_ACACIA_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_ACACIA_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_ACACIA_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_ACACIA_LOG, Blocks.ACACIA_SLAB, Blocks.BLACK_CONCRETE)

    val DARK_OAK_MEDIUM_DRAWER_BOX = BoxItem(Blocks.DARK_OAK_SLAB)
    val WHITE_DARK_OAK_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_DARK_OAK_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_DARK_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_DARK_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_DARK_OAK_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_DARK_OAK_LOG, Blocks.DARK_OAK_SLAB, Blocks.BLACK_CONCRETE)

    val MANGROVE_MEDIUM_DRAWER_BOX = BoxItem(Blocks.MANGROVE_SLAB)
    val WHITE_MANGROVE_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_MANGROVE_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_MANGROVE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_MANGROVE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_MANGROVE_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_MANGROVE_LOG, Blocks.MANGROVE_SLAB, Blocks.BLACK_CONCRETE)

    val CHERRY_MEDIUM_DRAWER_BOX = BoxItem(Blocks.CHERRY_SLAB)
    val WHITE_CHERRY_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_CHERRY_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_CHERRY_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_CHERRY_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.BLACK_CONCRETE)
    val WHITE_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.WHITE_CONCRETE)
    val BLACK_STRIPPED_CHERRY_LOG_KITCHEN_DRAWER_CASE = KitchenDrawerCaseItem(Blocks.STRIPPED_CHERRY_LOG, Blocks.CHERRY_SLAB, Blocks.BLACK_CONCRETE)

    override fun onRegistry(item: Item) {
        RegistryHelper.Items.NEW_ITEMS.add(item)
        if(item is BoxItem) RegistryHelper.Items.KITCHEN_DRAWERS_BOXES.add(item)
        if(item is KitchenDrawerCaseItem) RegistryHelper.Items.KITCHEN_DRAWERS_CASES.add(item)
    }
}